const Hotel = require("../../models/Hotel");
const Room = require("../../models/Room");
const destination = require("../../models/Destination");
const location = require("../../models/Location");
const Car = require("../../models/Car");

/* ========================
   CREATE HOTEL
======================== */
exports.createhotel = async (req, res) => {
  try {
    const hotelData = { ...req.body };

    // Parse your amenities string safely from FormData
    if (req.body.amenities) {
      hotelData.amenities = req.body.amenities.split(",").map(item => item.trim());
    }

    // Attach file path generated by multer
    if (req.file) {
      hotelData.image = `/uploads/${req.file.filename}`;
    }

    const hotel = await Hotel.create(hotelData);

    const populatedHotel = await Hotel.findById(hotel._id)
      .populate("destination", "name")
      .populate("location", "name");

    res.status(201).json({
      message: "Hotel created successfully",
      data: populatedHotel,
      status_code: 201,
    });
  } catch (err) {
    // 🔍 LOOK AT YOUR NODE.JS TERMINAL FOR THIS LOG:
    console.log("❌ EXPLICIT MONGOOSE VALIDATION ERROR:", err.message);
    
    res.status(400).json({
      error: err.message,
    });
  }
};

/* ========================
   GET ALL HOTELS
======================== */
exports.gethotel = async (req, res) => {
  try {
    const hotels = await Hotel.find()
      .populate("destination", "name")
      .populate("location", "name")
      .populate({
        path: "rooms",
        select: "roomType -_id",
      })
      .lean();

    // ✅ Keeping destination and location as objects so React can use ._id and .name
    const formattedHotels = hotels.map((hotel) => ({
      ...hotel,
      destination: hotel.destination ? { _id: hotel.destination._id, name: hotel.destination.name } : null,
      location: hotel.location ? { _id: hotel.location._id, name: hotel.location.name } : null,
      image: hotel.image || "",
      rooms: hotel.rooms ? hotel.rooms.map((room) => room.roomType) : [],
    }));

    res.status(200).json({
      message: "Hotels fetched successfully",
      data: formattedHotels,
      status_code: 200,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

exports.searchHotels = async (req, res) => {
  try {
    const { keyword } = req.query;

    const hotels = await Hotel.find()
      .populate("destination", "name")
      .populate("location", "name")
      .lean();

    const filteredHotels = hotels.filter(
      (hotel) =>
        hotel.destination?.name
          ?.toLowerCase()
          .includes(
            keyword.toLowerCase()
          ) ||
        hotel.location?.name
          ?.toLowerCase()
          .includes(
            keyword.toLowerCase()
          )
    );

    const formattedHotels =
      filteredHotels.map((hotel) => ({
        ...hotel,
        destination:
          hotel.destination?.name || "",
        location:
          hotel.location?.name || "",
      }));

    res.status(200).json({
      message:
        "Hotels fetched successfully",
      data: formattedHotels,
      status_code: 200,
    });
  } catch (err) {
    res.status(500).json({
      error: err.message,
    });
  }
};

/* ========================
   GET SINGLE HOTEL
======================== */
exports.gethotelbyid = async (req, res) => {
  try {
    const hotel = await Hotel.findById(req.params.id)
      .populate("destination", "name")
      .populate("location", "name")
      .populate({
        path: "rooms",
        select: "roomType -_id",
      })
      .lean();

    if (!hotel) {
      return res.status(404).json({ message: "Hotel not found" });
    }

    res.status(200).json({
      message: "Hotel fetched successfully",
      data: hotel,
      status_code: 200,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

/* ========================
   UPDATE HOTEL
======================== */
exports.updatehotel = async (req, res) => {
  try {
    const updateData = { ...req.body };

    // Parse incoming amenities string correctly
    if (req.body.amenities) {
      if (typeof req.body.amenities === "string") {
        if (req.body.amenities.startsWith("[")) {
          updateData.amenities = JSON.parse(req.body.amenities);
        } else {
          updateData.amenities = req.body.amenities.split(",").map(item => item.trim());
        }
      }
    }

    if (req.file) {
      updateData.image = `/uploads/${req.file.filename}`;
    }

    const hotel = await Hotel.findByIdAndUpdate(req.params.id, updateData, { new: true })
      .populate("destination", "name")
      .populate("location", "name")
      .populate({
        path: "rooms",
        select: "roomType -_id",
      })
      .lean();

    if (!hotel) {
      return res.status(404).json({ error: "Hotel not found" });
    }

    res.status(200).json({
      message: "Hotel updated successfully",
      data: hotel,
      status_code: 200,
    });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

/* ========================
   DELETE HOTEL
======================== */
exports.deletehotel = async (req, res) => {
  try {
    const hotel = await Hotel.findByIdAndDelete(req.params.id);

    if (!hotel) {
      return res.status(404).json({ error: "Hotel not found" });
    }

    await Room.deleteMany({ hotel: req.params.id });

    res.status(200).json({
      message: "Hotel and related rooms deleted successfully",
      status_code: 200,
    });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};
